spring.application.name=spring-homework003

spring.datasource.url= ${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USER}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.sql.init.mode=always
# Since you aren't using JPA/Hibernate for tables, 
# you can disable hibernate's auto-ddl to avoid confusion
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect